### ISSUE TITLE
helm plugin to interact with helm-registry

### ISSUE THREAD

**Issue by weiwei04** [caicloud/helm-registry#27]
See github.com/weiwei04/helm-registry-plugin, a prototype.

I am not sure if helm-registry needs a plugin like this, if helm-registry needs a plugin like this, I can open a pr and contribute it into helm-registry :)

**Comment by kdada** [comment]
It's a nice plugin for helm-registry. You can write a complete doc for the plugin. We really appreciate that you can issue a pr for the plugin.
