### ISSUE TITLE
How to get requirements.yaml of a chart?

### ISSUE THREAD

**Issue by mixj93** [caicloud/helm-registry#37]
**What is the issue about**:
Want to get `requirements.yaml` of a chart and don't know how.

**What happened**:
I try to get `requirements.yaml` using `DownloadVersion`, but it seems `requirements.yaml` is not included.

**What you expected to happen**:
get `requirements.yaml`

**Anything else we need to know**:

**Comment by mixj93** [comment]
I'm a little bit confused.

`requirements.yaml` is a common file in chart. [For example](https://docs.helm.sh/developing_charts/#the-chart-file-structure):
![image](https://user-images.githubusercontent.com/12998118/35435831-20ee3af8-02c7-11e8-8565-e818a073f1bf.png)

 And I can get `README.md`, `OWNERS` using `DownloadVersion`, and `requirements.yaml`is in the same directory with them, but I cannot get it.

**Comment by kdada** [comment]
The result of `DownloadVersion` is the archived data of a chart. You could simply save it to a file. Then unarchive it by  `tar -xzvf /path/to/file`. You could see files in it.

**Comment by mixj93** [comment]
I do stuff like this:
```
data, _ := r.client.DownloadVersion(space, chart, ver)
ch, _ := chartutil.LoadArchive(bytes.NewReader(data))
for _, f := range ch.Files {
    fmt.Println("### f:", f.TypeUrl)
}
```
this code prints `README.md` but it doesn't print `requirements.yaml` and It seems this file can be got in pervious version🤔

**Comment by kdada** [comment]
How did you generate the new version? Created by orchestration or updated a `.tgz`?
The former should not have a `requirements.yaml`. The latter may depends on what you uploaded.
